### ISSUE TITLE
Unhandled exception with GoogleApi.Logging.V2.Api.Entries.logging_entries_list

### ISSUE THREAD

**Issue by absolutejam** [googleapis/elixir-google-api#1109]
Called via.
```
 {:ok, token} = Goth.Token.for_scope("https://www.googleapis.com/auth/logging.read")
    conn = GoogleApi.Logging.V2.Connection.new(token.token)    

    req = %GoogleApi.Logging.V2.Model.ListLogEntriesRequest{
      projectIds: ["myproject"],
    }

    GoogleApi.Logging.V2.Api.Entries.logging_entries_list(
      conn,
      body: req
    )
```

```
** (FunctionClauseError) no function clause matching in Keyword.merge/2    
    
    The following arguments were given to Keyword.merge/2:
    
        # 1
        %{
          as: %GoogleApi.Logging.V2.Model.ListLogEntriesResponse{
            entries: nil,
            nextPageToken: nil
          }
        }
    
        # 2
        [
          as: [
            %GoogleApi.Logging.V2.Model.LogEntry{
              httpRequest: nil,
              insertId: nil,
              jsonPayload: nil,
              labels: nil,
              logName: nil,
              operation: nil,
              protoPayload: nil,
              receiveTimestamp: nil,
              resource: nil,
              severity: nil,
              sourceLocation: nil,
              textPayload: nil,
              timestamp: nil,
              trace: nil
            }
          ]
        ]
    
    Attempted function clauses (showing 3 out of 3):
    
        def merge(keywords1, []) when is_list(keywords1)
        def merge([], keywords2) when is_list(keywords2)
        def merge(keywords1, keywords2) when is_list(keywords1) and is_list(keywords2)
    
    (elixir) lib/keyword.ex:707: Keyword.merge/2
    (google_api_logging) lib/google_api/logging/v2/deserializer.ex:31: anonymous fn/3 in GoogleApi.Logging.V2.Deserializer.deserialize/5
    (elixir) lib/map.ex:752: Map.update!/3
    (poison) lib/poison.ex:87: Poison.decode!/2
    (poison) lib/poison.ex:62: Poison.decode/2
```

Tried manually mangling the deserializer to wrap `#1` in a keyword list but just hit another issue and didn't want to prod too far based on the advertised instability of this package.

**Comment by zeroasterisk** [comment]
Do you think it is related to Poison version 4? See #1232 for a summary.  
Can you downgrade Poison and see if that fixes it?

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
