### ISSUE TITLE
Struggle integrating FCM Api with phoenix

### ISSUE THREAD

**Issue by ykostov** [googleapis/elixir-google-api#11837]
Howdy Devs,
I've been trying to connect my phoenix project to the firebase in order to use the FCM. This may look like a rookie question, but I have read the docs and have tried many ways to do the connection, in which apparently I am missing something. 

So basically i have this code
```
defmodule MyApp.Firebase do
  alias GoogleApi.FCM.V1.Connection
  alias GoogleApi.FCM.V1.Api.Projects
  alias GoogleApi.FCM.V1.Model.SendMessageRequest

  @project_id "project-code"

  def send_message do
    {:ok, token} = Goth.Token.for_scope("https://www.googleapis.com/auth/firebase.messaging")

    conn = Connection.new(token.token)
    
    message_request = %SendMessageRequest{
      message: %{
        token: "device-token",
        notification: %{
          title: "Hello",
          body: "World"
        }
      }
    }

    case Projects.fcm_projects_messages_send(conn, @project_id, message_request) do
      {:ok, response} ->
        IO.inspect(response)
        :ok

      {:error, reason} ->
        IO.inspect(reason)
        {:error, reason}
    end
  end
end
```
I have configured my service json with goth:
```
config :goth, json: File.read!("config/firebase-config.json")
```
and this is my mix:
```
 {:goth, "~> 1.3"},
  {:google_api_fcm, "~> 0.7"},
  {:google_api_storage, "~> 0.19.0"}    
```

So, I get this error:
`** (FunctionClauseError) no function clause matching in GoogleApi.Gax.Request.add_optional_params/3 `

I tried to upgrade gax from 0.4.0 to 0.4.1 but same error.

```
The following arguments were given to GoogleApi.Gax.Request.add_optional_params/3:
    
        # 1
        %GoogleApi.Gax.Request{
          method: :post,
          url: "/v1/projectcode/messages:send",
          body: [],
          query: [],
          file: [],
          header: [],
          library_version: ""
        }
    
        # 2
        %{
          callback: :query,
          fields: :query,
          key: :query,
          body: :body,
          alt: :query,
          "$.xgafv": :query,
          access_token: :query,
          oauth_token: :query,
          prettyPrint: :query,
          quotaUser: :query,
          uploadType: :query,
          upload_protocol: :query
        }
    
        # 3
        %GoogleApi.FCM.V1.Model.SendMessageRequest{
          validateOnly: nil,
          message: %{
            token: "device-token",
            notification: %{title: "Hello", body: "World"}
          }
        }
    
    Attempted function clauses (showing 2 out of 2):
    
        def add_optional_params(request, _, [])
        def add_optional_params(request, definitions, [{key, value} | tail])
    
    (google_gax 0.4.1) lib/google_api/gax/request.ex:137: GoogleApi.Gax.Request.add_optional_params/3
    (google_api_fcm 0.12.0) lib/google_api/fcm/v1/api/projects.ex:82: GoogleApi.FCM.V1.Api.Projects.fcm_projects_messages_send/4
    (app 0.1.0) lib/app/firebase.ex:23: App.Firebase.send_message/0
    iex:4: (file)
```

Any thoughts? What am i missing? 

Have a nice day :)

**Comment by ykostov** [comment]
About me question - still not quite sure where I did wrong, however I (re)discovered [Pigeon v.2](https://hexdocs.pm/pigeon/2.0.0-rc.0/Pigeon.FCM.html) which makes things simple :) Closing this out.
